  <section class="py-12 px-4 sm:px-8">
    <div class="max-w-7xl mx-auto">
      <h2 class="text-3xl font-bold text-center mb-10 text-[#b30d0d] uppercase">
        Customer Reviews
      </h2>

      <div class="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <!-- Review List -->
        <div id="review-list" class="space-y-4 max-h-[500px] overflow-y-auto pr-2">
          <!-- Reviews will be inserted here -->
        </div>

        <!-- Write Review Form -->
        <form id="review-form" class="bg-white p-6 rounded-xl shadow-xl space-y-4">
          <h3 class="text-xl font-semibold text-[#b30d0d] mb-2 text-center">
            Write a Review
          </h3>

          <input
            type="text"
            name="title"
            placeholder="Review Title"
            class="w-full border border-gray-300 rounded px-4 py-2 focus:ring-2 focus:ring-red-400"
            required
          />

          <!-- Star Rating -->
          <div class="flex items-center gap-1 text-2xl" id="star-container">
            <!-- Stars will be generated by JS -->
          </div>

          <input
            type="text"
            name="name"
            placeholder="Your Name"
            class="w-full border border-gray-300 rounded px-4 py-2 focus:ring-2 focus:ring-red-400"
            required
          />

          <textarea
            name="review"
            placeholder="Your Review"
            rows="4"
            class="w-full border border-gray-300 rounded px-4 py-2 focus:ring-2 focus:ring-red-400"
            required
          ></textarea>

          <button
            type="submit"
            class="w-full bg-[#d60000] hover:bg-red-700 text-white py-2 rounded font-semibold"
          >
            Submit Review
          </button>
        </form>
      </div>
    </div>
  </section>

  <script>
    const reviews = [
      {
        title: "Excellent Service",
        rating: 5,
        name: "Anjali Sharma",
        review: "Very professional and reliable service. Highly recommended!",
        date: "18/07/2025"
      },
      {
        title: "Good Experience",
        rating: 4,
        name: "Rahul Verma",
        review: "The team was quick and efficient. Great job overall.",
        date: "15/07/2025"
      },
      {
        title: "Satisfied Customer",
        rating: 5,
        name: "Preeti Desai",
        review: "Everything was smooth from start to finish. Loved it!",
        date: "12/07/2025"
      }
    ];

    const reviewList = document.getElementById("review-list");
    const reviewForm = document.getElementById("review-form");
    const starContainer = document.getElementById("star-container");
    let selectedRating = 0;

    function renderStars(selected = 0) {
      starContainer.innerHTML = "";
      for (let i = 1; i <= 5; i++) {
        const star = document.createElement("span");
        star.textContent = "★";
        star.className = `cursor-pointer ${i <= selected ? "text-yellow-400" : "text-gray-300"}`;
        star.addEventListener("click", () => {
          selectedRating = i;
          renderStars(selectedRating);
        });
        starContainer.appendChild(star);
      }
    }

    function renderReviews() {
      reviewList.innerHTML = "";
      if (reviews.length === 0) {
        reviewList.innerHTML = `<p class="text-gray-500 text-center">No reviews yet. Be the first to write one!</p>`;
        return;
      }

      reviews.forEach(({ title, rating, name, review, date }) => {
        const card = document.createElement("div");
        card.className = "bg-white p-5 rounded-xl shadow hover:shadow-md transition duration-300";
        card.innerHTML = `
          <h4 class="text-lg font-semibold text-[#333]">${title}</h4>
          <div class="text-yellow-400 text-sm mb-1">${"★".repeat(rating)}${"☆".repeat(5 - rating)}</div>
          <p class="text-gray-700 text-sm mb-2">${review}</p>
          <p class="text-xs text-gray-500">- ${name}, ${date}</p>
        `;
        reviewList.appendChild(card);
      });
    }

    reviewForm.addEventListener("submit", function (e) {
      e.preventDefault();

      const formData = new FormData(reviewForm);
      const title = formData.get("title").trim();
      const name = formData.get("name").trim();
      const reviewText = formData.get("review").trim();

      if (!title || !name || !reviewText || selectedRating === 0) {
        alert("Please fill all fields and select a rating.");
        return;
      }

      const today = new Date();
      const date = today.toLocaleDateString("en-GB"); // dd/mm/yyyy

      reviews.unshift({
        title,
        name,
        review: reviewText,
        rating: selectedRating,
        date
      });

      renderReviews();
      reviewForm.reset();
      selectedRating = 0;
      renderStars();
    });

    // Initial render
    renderReviews();
    renderStars();
  </script>